import { Box, Button, Grid } from "@chakra-ui/react";
import React, { useState } from "react";

export const Calculator = () => {
  const [display, setDisplay] = useState("");

  const handleClick = (el) => {
    // setDisplay((prev) => prev + e);
    console.log(el);
  };

  return (
    <Box
      width={"30%"}
      height={"650px"}
      bgGradient="linear(to-b, #9d4491, #a73e7f, #be3754,#c82e45)"
      margin={"auto"}
      marginTop={"100px"}
      padding={"20px"}
    >
      <Box
        width={"80%"}
        height={"90%"}
        backgroundColor={"black"}
        margin={"auto"}
        marginTop={"20px"}
      >
        <Box width={"30%"} height={"100px"} color={"white"}>
          {display}
        </Box>
        <Grid templateColumns={"repeat(4, 1fr)"} gap={"10px"} padding={"10px"}>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#a4a4a5"}
            onClick={(c) => handleClick(c)}
          >
            C
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#a4a4a5"}
            onClick={handleClick}
          >
            +/-
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#a4a4a5"}
            onClick={handleClick}
          >
            %
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#fe951a"}
            color={"white"}
            onClick={handleClick}
          >
            /
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#333232"}
            color={"white"}
            onClick={handleClick}
          >
            7
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#333232"}
            color={"white"}
            onClick={handleClick}
          >
            8
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#333232"}
            color={"white"}
            onClick={handleClick}
          >
            9
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#fe951a"}
            color={"white"}
            onClick={handleClick}
          >
            X
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#333232"}
            color={"white"}
            onClick={handleClick}
          >
            4
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#333232"}
            color={"white"}
            onClick={handleClick}
          >
            5
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#333232"}
            color={"white"}
            onClick={handleClick}
          >
            6
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#fe951a"}
            color={"white"}
            onClick={handleClick}
          >
            -
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#333232"}
            color={"white"}
            onClick={handleClick}
          >
            1
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#333232"}
            color={"white"}
            onClick={handleClick}
          >
            2
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#333232"}
            color={"white"}
            onClick={handleClick}
          >
            3
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#fe951a"}
            color={"white"}
            onClick={handleClick}
          >
            +
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#333232"}
            color={"white"}
            onClick={handleClick}
          >
            #
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#333232"}
            color={"white"}
            onClick={handleClick}
          >
            0
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#333232"}
            color={"white"}
            onClick={handleClick}
          >
            .
          </Button>
          <Button
            borderRadius={"50%"}
            height={"70px"}
            backgroundColor={"#fe951a"}
            color={"white"}
            onClick={handleClick}
          >
            =
          </Button>
        </Grid>
      </Box>
    </Box>
  );
};
